# Generated by Django 4.2.14 on 2024-07-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdharCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cource_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("father_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                (
                    "adhar_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="adhar_card",
                        serialize=False,
                        to="relationship_app.adharcard",
                    ),
                ),
                (
                    "cources",
                    models.ManyToManyField(
                        related_name="cources", to="relationship_app.cources"
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="designation",
                        to="relationship_app.designation",
                    ),
                ),
            ],
        ),
    ]
