# Generated by Django 4.2.15 on 2024-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_services", "0002_alter_user_gender_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_profiles",
                to="user_services.role",
            ),
        ),
    ]
